---
# Global Variables for 'hypervisors' Inventory Group

dvr: "on"
dhcp: "off"
snat: "off"
ceilometer: "on"
glance: "off"
nova_instances_path: /opt/pf9/data/instances/
neutron_dhcp_dnsmasq_dns_servers: 8.8.8.8
neutron_ovs_allow_dhcp_vms: "False"
neutron_ovs_bridge_name: "br-pf9"
neutron_ovs_bridge_mappings: "external:br-pf9"
ceilometer_kvm_instance_disk_path: /opt/pf9/data/instances/
ceilometer_customize: "False"
ceilometer_cpu_interval: 600
