---
# Global Variables for 'hypervisors' Inventory Group

live_migration: True
nested_virt: "False"
kernel_same_page_merging: "False"
dhcp: "off"
snat: "off"
ceilometer: "on"
glance: "off"
multipath: False
nova_instances_path: /opt/pf9/data/instances/
neutron_ovs_allow_dhcp_vms: "False"
neutron_ovs_bridge_name: "br-pf9"
neutron_ovs_bridge_mappings: "external:br-pf9"
ceilometer_customize: "False"
ceilometer_cpu_interval: 600
