---
# Assign pf9-kube in resmgr

# Get hostid 
- name: validate pf9/host_id.conf
  stat:
    path: /etc/pf9/host_id.conf
  register: stat_hostid
  failed_when: stat_hostid.stat.exists == false

- name: get host_id
  shell: cat /etc/pf9/host_id.conf | grep ^host_id | cut -d = -f2 | cut -d ' ' -f2
  register: host_id_raw

- name: Set fact host_id
  set_fact:
    host_id: "{{ host_id_raw.stdout.strip() }}"

# Role Assignment 
- name: "Assigning Role - {{rolename}}"
  uri:
    url: "https://{{du_fqdn}}/resmgr/v1/hosts/{{host_id}}/roles/{{rolename}}"
    method: PUT
    validate_certs: False
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ os_auth_token }}"
  register: assign_role_result
  #delegate_to: localhost

- name: DEBUGGING assign_role_result
  debug:
    var: assign_role_result
    verbosity: 1
