---
- name: Check if cached Keystone token exists
  file:
    state: file
    name: files/keystone-token.txt
  ignore_errors: True
  register: cached_token

- block:
    - name: Load OS_AUTH_TOKEN into fact
      set_fact: "os_auth_token={{ lookup('file', 'keystone-token.txt') | trim }}"

    - name: Validate Keystone token
      uri:
        url: "{{ du_url }}/keystone/v2.0"
        headers:
          X-Auth-Token: "{{ os_auth_token }}"
        status_code: 200, 401
        validate_certs: no
      register: validate_response
  when: cached_token|success

- block:
    - name: Obtain authentication token from Keystone
      os_auth:
        auth:
          auth_url: "{{ du_url }}/keystone/v2.0"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_tenant }}"
        region_name: "{{ os_region }}"
        validate_certs: False
      always_run: True
      register: auth_reply

    - name: Save OS Auth Token
      copy:
        content: "{{ auth_reply.ansible_facts.auth_token }}"
        dest: files/keystone-token.txt

    - name: Store OS_AUTH_TOKEN in fact
      set_fact: "os_auth_token={{ auth_reply.ansible_facts.auth_token }}"

  when: cached_token|failed or
    (validate_response is defined and validate_response.status != 200)
